steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v1.0.1']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '-t', 'gcr.io/$PROJECT_ID/test:latest', '--push', '.']
  #   id: 'build-multi-architecture-container-image'
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #!/usr/bin/env bash
      ./build-ci.sh gcr.io/sre-docker-registry/py-node ${SHA:0:8}-${ID:0:8}
    env:
    - 'SHA=$COMMIT_SHA'
    - 'ID=$BUILD_ID'
# substitutions:
#     _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm/v7,linux/arm64'

timeout: 6h
options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  machineType: 'E2_HIGHCPU_8'
