steps:
- name: 'gcr.io/cloud-builders/docker'
  script: ./build-all.sh gcr.io/sre-docker-registry/py-node $SHA-$ID
  env:
  - 'SHA=${COMMIT_SHA:0:10}'
  - 'ID=$BUILD_ID'
images: ['gcr.io/sre-docker-registry/py-node']
timeout: 3h
options:
  machineType: 'E2_HIGHCPU_8'
